name: 'next-env'
description: 'Loads .env variables in Next.js projects and sets them as GitHub Action Secrets.'
author: 'Stefan Natter (https://natterstefan.me)'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'sliders'
  color: 'green'
inputs:
  environment:
    required: true
    description: 'Define which environment you want to load: development, test or production.'
    default: 'development'
