name: 'next-env'
description: 'Read .env.[development|test|production][.local] files in Next.js projects and add variables as secrets to GITHUB_ENV'
author: 'Stefan Natter (https://natterstefan.me)'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'sliders'
  color: 'green'
inputs:
  environment:
    required: true
    description: 'Define which environment you want to load: development, test or production.'
    default: 'development'
  path:
    required: false
    description: 'Define the path to the folder with the `.env` files.'
    default: '.'
